.code
	priv r1, r0, r0, 3
	xor r2, r2, r2
	addi r2, 0
	shftli r2, 12
	addi r2, 0
	shftli r2, 12
	addi r2, 0
	shftli r2, 12
	addi r2, 0
	shftli r2, 12
	addi r2, 0
	shftli r2, 4
	addi r2, 1
	xor r5, r5, r5
	addi r5, 0
	shftli r5, 12
	addi r5, 0
	shftli r5, 12
	addi r5, 0
	shftli r5, 12
	addi r5, 1
	shftli r5, 12
	addi r5, 2154
	shftli r5, 4
	addi r5, 0
	xor r24, r24, r24
	addi r24, 0
	shftli r24, 12
	addi r24, 0
	shftli r24, 12
	addi r24, 0
	shftli r24, 12
	addi r24, 0
	shftli r24, 12
	addi r24, 525
	shftli r24, 4
	addi r24, 12
	brgt r24, r2, r1
	priv r3, r0, r0, 3
	mov (r5)(0), r3
	addi r5, 8
	addi r2, 1
	xor r24, r24, r24
	addi r24, 0
	shftli r24, 12
	addi r24, 0
	shftli r24, 12
	addi r24, 0
	shftli r24, 12
	addi r24, 0
	shftli r24, 12
	addi r24, 518
	shftli r24, 4
	addi r24, 4
	br r24
	xor r5, r5, r5
	addi r5, 0
	shftli r5, 12
	addi r5, 0
	shftli r5, 12
	addi r5, 0
	shftli r5, 12
	addi r5, 1
	shftli r5, 12
	addi r5, 2154
	shftli r5, 4
	addi r5, 0
	priv r4, r0, r0, 3
	xor r6, r6, r6
	mov r7, r1
	subi r7, 1
	xor r24, r24, r24
	addi r24, 0
	shftli r24, 12
	addi r24, 0
	shftli r24, 12
	addi r24, 0
	shftli r24, 12
	addi r24, 0
	shftli r24, 12
	addi r24, 574
	shftli r24, 4
	addi r24, 8
	brgt r24, r6, r7
	add r8, r0, r7
	sub r8, r8, r6
	shftri r8, 1
	add r8, r8, r6
	xor r11, r11, r11
	addi r11, 0
	shftli r11, 12
	addi r11, 0
	shftli r11, 12
	addi r11, 0
	shftli r11, 12
	addi r11, 0
	shftli r11, 12
	addi r11, 0
	shftli r11, 4
	addi r11, 8
	mul r9, r8, r11
	add r9, r9, r5
	mov r10, (r9)(0)
	xor r24, r24, r24
	addi r24, 0
	shftli r24, 12
	addi r24, 0
	shftli r24, 12
	addi r24, 0
	shftli r24, 12
	addi r24, 0
	shftli r24, 12
	addi r24, 547
	shftli r24, 4
	addi r24, 8
	brgt r24, r4, r10
	xor r24, r24, r24
	addi r24, 0
	shftli r24, 12
	addi r24, 0
	shftli r24, 12
	addi r24, 0
	shftli r24, 12
	addi r24, 0
	shftli r24, 12
	addi r24, 551
	shftli r24, 4
	addi r24, 4
	brgt r24, r10, r4
	xor r24, r24, r24
	addi r24, 0
	shftli r24, 12
	addi r24, 0
	shftli r24, 12
	addi r24, 0
	shftli r24, 12
	addi r24, 0
	shftli r24, 12
	addi r24, 555
	shftli r24, 4
	addi r24, 0
	br r24
	addi r8, 1
	add r6, r0, r8
	xor r24, r24, r24
	addi r24, 0
	shftli r24, 12
	addi r24, 0
	shftli r24, 12
	addi r24, 0
	shftli r24, 12
	addi r24, 0
	shftli r24, 12
	addi r24, 529
	shftli r24, 4
	addi r24, 12
	br r24
	subi r8, 1
	add r7, r0, r8
	xor r24, r24, r24
	addi r24, 0
	shftli r24, 12
	addi r24, 0
	shftli r24, 12
	addi r24, 0
	shftli r24, 12
	addi r24, 0
	shftli r24, 12
	addi r24, 529
	shftli r24, 4
	addi r24, 12
	br r24
	xor r27, r27, r27
	addi r27, 0
	shftli r27, 12
	addi r27, 0
	shftli r27, 12
	addi r27, 0
	shftli r27, 12
	addi r27, 0
	shftli r27, 12
	addi r27, 0
	shftli r27, 4
	addi r27, 3
	xor r26, r26, r26
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 6
	shftli r26, 4
	addi r26, 6
	priv r27, r26, r0, 4
	xor r26, r26, r26
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 6
	shftli r26, 4
	addi r26, 15
	priv r27, r26, r0, 4
	xor r26, r26, r26
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 7
	shftli r26, 4
	addi r26, 5
	priv r27, r26, r0, 4
	xor r26, r26, r26
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 6
	shftli r26, 4
	addi r26, 14
	priv r27, r26, r0, 4
	xor r26, r26, r26
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 6
	shftli r26, 4
	addi r26, 4
	priv r27, r26, r0, 4
	priv r0, r0, r0, 0
	xor r27, r27, r27
	addi r27, 0
	shftli r27, 12
	addi r27, 0
	shftli r27, 12
	addi r27, 0
	shftli r27, 12
	addi r27, 0
	shftli r27, 12
	addi r27, 0
	shftli r27, 4
	addi r27, 3
	xor r26, r26, r26
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 6
	shftli r26, 4
	addi r26, 14
	priv r27, r26, r0, 4
	xor r26, r26, r26
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 6
	shftli r26, 4
	addi r26, 15
	priv r27, r26, r0, 4
	xor r26, r26, r26
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 7
	shftli r26, 4
	addi r26, 4
	priv r27, r26, r0, 4
	xor r26, r26, r26
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 2
	shftli r26, 4
	addi r26, 0
	priv r27, r26, r0, 4
	xor r26, r26, r26
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 6
	shftli r26, 4
	addi r26, 6
	priv r27, r26, r0, 4
	xor r26, r26, r26
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 6
	shftli r26, 4
	addi r26, 15
	priv r27, r26, r0, 4
	xor r26, r26, r26
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 7
	shftli r26, 4
	addi r26, 5
	priv r27, r26, r0, 4
	xor r26, r26, r26
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 6
	shftli r26, 4
	addi r26, 14
	priv r27, r26, r0, 4
	xor r26, r26, r26
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 6
	shftli r26, 4
	addi r26, 4
	priv r27, r26, r0, 4
	priv r0, r0, r0, 0
